include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_declarations:
      errors:
        invalid_annotation_target: ignore
        sort_pub_dependencies: true
        invalid_use_of_protected_member: error
