name: repoviewr
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flash: ^3.0.5+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.4
  http: ^1.1.2
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^7.0.7296
  material_floating_search_bar: ^0.3.7
  oauth2: ^2.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  sembast: ^3.5.0+1
  shimmer: ^3.0.0
  svg_flutter: ^0.0.1
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  material_floating_search_bar_2:
    git:
      url: https://github.com/bilalelsayed97/material_floating_search_bar.git
dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
